var express = require('express');
var router = express.Router();
//var z=require('./controller/entertainmentController');
var adminController=requrire('./controller/AdminController');
var corporateContorller=requrire('./controller/CorporateController');
var clientController=requrire('./controller/ClientController');

router.post('/entertainment',corporateContorller.add);
router.get('/home' ,corporateContorller.get);
router.post('/admin/remove',adminController.remove);
router.post('/corporate/remove',corporateContorller.remove);
router.get('/admin',adminController.getAllServices);
//router.get('/rate',z.rate);
router.post('/editEmail',corporateContorller.editEmail);
router.post('/editPrice',corporateContorller.editPrice);
router.post('/editPhone',corporateContorller.editPhone);
router.post('/editLocation',corporateContorller.editLocation);
router.post('/editName',corporateContorller.editName);
router.post('/rateEntertainment',clientController.rateEntertainment);
router.get('/edit',corporateContorller.edit);
router.get('/addEntertainment',corporateContorller.addEntertainment);
router.get('/corporate/entertainment',corporateContorller.getEntertainment);
router.get('viewClients',corporateContorller.viewClients);
module.exports = router;
